#! /bin/sh

bspc monitor HDMI-1 -d 1 2 3
bspc monitor DVI-I-1 -d 4 5 6
bspc wm -O HDMI-1 DVI-I-1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mpv state=floating follow=on
bspc rule -a nitrogen state=floating follow=on
