#! /bin/bash

PRIMARY_MONITOR=$(cat .config/variables/primary-monitor)
SECONDARY_MONITOR=$(cat .config/variables/secondary-monitor)

bspc monitor $PRIMARY_MONITOR -d 1 2 3
[[ -n "$SECONDARY_MONITOR" ]] && bspc monitor $SECONDARY_MONITOR -d 4 5 6

bspc wm -O $PRIMARY_MONITOR

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mpv state=floating follow=on
bspc rule -a nitrogen state=floating follow=on
