#! /bin/sh

bspc monitor DVI-I-1 -d 1 2 3
bspc monitor DVI-D-1 -d 4 5 6
bspc wm -O DVI-I-1 DVI-D-1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

